replicaCount: 2

image:
  repository: antonivanovdevops/wordpress
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress.k8s-2.sa

persistentVolumeClaim:
  storageSize: 8Gi

env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.202.4
  - name: WORDPRESS_DB_NAME
    value: bn_wordpress
  - name: WORDPRESS_DB_USER
    value: bn_wordpress
  - name: WORDPRESS_DB_PASSWORD
    value: bn_wordpress